#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_PruebaTecnica")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTablaCambioContraseña(TablaCambioContraseña instance);
    partial void UpdateTablaCambioContraseña(TablaCambioContraseña instance);
    partial void DeleteTablaCambioContraseña(TablaCambioContraseña instance);
    partial void InsertTablaUsuario(TablaUsuario instance);
    partial void UpdateTablaUsuario(TablaUsuario instance);
    partial void DeleteTablaUsuario(TablaUsuario instance);
    partial void InsertTablaEmpleado(TablaEmpleado instance);
    partial void UpdateTablaEmpleado(TablaEmpleado instance);
    partial void DeleteTablaEmpleado(TablaEmpleado instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Datos.Properties.Settings.Default.DB_PruebaTecnicaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TablaCambioContraseña> TablaCambioContraseñas
		{
			get
			{
				return this.GetTable<TablaCambioContraseña>();
			}
		}
		
		public System.Data.Linq.Table<TablaUsuario> TablaUsuarios
		{
			get
			{
				return this.GetTable<TablaUsuario>();
			}
		}
		
		public System.Data.Linq.Table<TablaEmpleado> TablaEmpleados
		{
			get
			{
				return this.GetTable<TablaEmpleado>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TablaCambioContraseña")]
	public partial class TablaCambioContraseña : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Token;
		
		private int _IdUsuario;
		
		private bool _Utiliazado;
		
		private System.DateTime _FechaVencimiento;
		
		private EntityRef<TablaUsuario> _TablaUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTokenChanging(System.Guid value);
    partial void OnTokenChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnUtiliazadoChanging(bool value);
    partial void OnUtiliazadoChanged();
    partial void OnFechaVencimientoChanging(System.DateTime value);
    partial void OnFechaVencimientoChanged();
    #endregion
		
		public TablaCambioContraseña()
		{
			this._TablaUsuario = default(EntityRef<TablaUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Token", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Token
		{
			get
			{
				return this._Token;
			}
			set
			{
				if ((this._Token != value))
				{
					this.OnTokenChanging(value);
					this.SendPropertyChanging();
					this._Token = value;
					this.SendPropertyChanged("Token");
					this.OnTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._TablaUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Utiliazado", DbType="Bit NOT NULL")]
		public bool Utiliazado
		{
			get
			{
				return this._Utiliazado;
			}
			set
			{
				if ((this._Utiliazado != value))
				{
					this.OnUtiliazadoChanging(value);
					this.SendPropertyChanging();
					this._Utiliazado = value;
					this.SendPropertyChanged("Utiliazado");
					this.OnUtiliazadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVencimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaVencimiento
		{
			get
			{
				return this._FechaVencimiento;
			}
			set
			{
				if ((this._FechaVencimiento != value))
				{
					this.OnFechaVencimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaVencimiento = value;
					this.SendPropertyChanged("FechaVencimiento");
					this.OnFechaVencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TablaUsuario_TablaCambioContraseña", Storage="_TablaUsuario", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public TablaUsuario TablaUsuario
		{
			get
			{
				return this._TablaUsuario.Entity;
			}
			set
			{
				TablaUsuario previousValue = this._TablaUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TablaUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TablaUsuario.Entity = null;
						previousValue.TablaCambioContraseñas.Remove(this);
					}
					this._TablaUsuario.Entity = value;
					if ((value != null))
					{
						value.TablaCambioContraseñas.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(int);
					}
					this.SendPropertyChanged("TablaUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TablaUsuario")]
	public partial class TablaUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _Email;
		
		private string _Contraseña;
		
		private string _Nombre;
		
		private System.DateTime _FechaNacimiento;
		
		private EntitySet<TablaCambioContraseña> _TablaCambioContraseñas;
		
		private EntitySet<TablaEmpleado> _TablaEmpleados;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaNacimientoChanging(System.DateTime value);
    partial void OnFechaNacimientoChanged();
    #endregion
		
		public TablaUsuario()
		{
			this._TablaCambioContraseñas = new EntitySet<TablaCambioContraseña>(new Action<TablaCambioContraseña>(this.attach_TablaCambioContraseñas), new Action<TablaCambioContraseña>(this.detach_TablaCambioContraseñas));
			this._TablaEmpleados = new EntitySet<TablaEmpleado>(new Action<TablaEmpleado>(this.attach_TablaEmpleados), new Action<TablaEmpleado>(this.detach_TablaEmpleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TablaUsuario_TablaCambioContraseña", Storage="_TablaCambioContraseñas", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<TablaCambioContraseña> TablaCambioContraseñas
		{
			get
			{
				return this._TablaCambioContraseñas;
			}
			set
			{
				this._TablaCambioContraseñas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TablaUsuario_TablaEmpleado", Storage="_TablaEmpleados", ThisKey="IdUsuario", OtherKey="IdUsuarioCreacion")]
		public EntitySet<TablaEmpleado> TablaEmpleados
		{
			get
			{
				return this._TablaEmpleados;
			}
			set
			{
				this._TablaEmpleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TablaCambioContraseñas(TablaCambioContraseña entity)
		{
			this.SendPropertyChanging();
			entity.TablaUsuario = this;
		}
		
		private void detach_TablaCambioContraseñas(TablaCambioContraseña entity)
		{
			this.SendPropertyChanging();
			entity.TablaUsuario = null;
		}
		
		private void attach_TablaEmpleados(TablaEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.TablaUsuario = this;
		}
		
		private void detach_TablaEmpleados(TablaEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.TablaUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TablaEmpleado")]
	public partial class TablaEmpleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdEmpleado;
		
		private int _DPI;
		
		private string _Nombre;
		
		private decimal _Hijo;
		
		private decimal _SalarioBase;
		
		private string _Estado;
		
		private int _IdUsuarioCreacion;
		
		private System.DateTime _FechaCreacion;
		
		private EntityRef<TablaUsuario> _TablaUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEmpleadoChanging(int value);
    partial void OnIdEmpleadoChanged();
    partial void OnDPIChanging(int value);
    partial void OnDPIChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnHijoChanging(decimal value);
    partial void OnHijoChanged();
    partial void OnSalarioBaseChanging(decimal value);
    partial void OnSalarioBaseChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnIdUsuarioCreacionChanging(int value);
    partial void OnIdUsuarioCreacionChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public TablaEmpleado()
		{
			this._TablaUsuario = default(EntityRef<TablaUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdEmpleado
		{
			get
			{
				return this._IdEmpleado;
			}
			set
			{
				if ((this._IdEmpleado != value))
				{
					this.OnIdEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._IdEmpleado = value;
					this.SendPropertyChanged("IdEmpleado");
					this.OnIdEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPI", DbType="Int NOT NULL")]
		public int DPI
		{
			get
			{
				return this._DPI;
			}
			set
			{
				if ((this._DPI != value))
				{
					this.OnDPIChanging(value);
					this.SendPropertyChanging();
					this._DPI = value;
					this.SendPropertyChanged("DPI");
					this.OnDPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hijo", DbType="Decimal(2,0) NOT NULL")]
		public decimal Hijo
		{
			get
			{
				return this._Hijo;
			}
			set
			{
				if ((this._Hijo != value))
				{
					this.OnHijoChanging(value);
					this.SendPropertyChanging();
					this._Hijo = value;
					this.SendPropertyChanged("Hijo");
					this.OnHijoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalarioBase", DbType="Decimal(7,2) NOT NULL")]
		public decimal SalarioBase
		{
			get
			{
				return this._SalarioBase;
			}
			set
			{
				if ((this._SalarioBase != value))
				{
					this.OnSalarioBaseChanging(value);
					this.SendPropertyChanging();
					this._SalarioBase = value;
					this.SendPropertyChanged("SalarioBase");
					this.OnSalarioBaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioCreacion", DbType="Int NOT NULL")]
		public int IdUsuarioCreacion
		{
			get
			{
				return this._IdUsuarioCreacion;
			}
			set
			{
				if ((this._IdUsuarioCreacion != value))
				{
					if (this._TablaUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioCreacion = value;
					this.SendPropertyChanged("IdUsuarioCreacion");
					this.OnIdUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TablaUsuario_TablaEmpleado", Storage="_TablaUsuario", ThisKey="IdUsuarioCreacion", OtherKey="IdUsuario", IsForeignKey=true)]
		public TablaUsuario TablaUsuario
		{
			get
			{
				return this._TablaUsuario.Entity;
			}
			set
			{
				TablaUsuario previousValue = this._TablaUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TablaUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TablaUsuario.Entity = null;
						previousValue.TablaEmpleados.Remove(this);
					}
					this._TablaUsuario.Entity = value;
					if ((value != null))
					{
						value.TablaEmpleados.Add(this);
						this._IdUsuarioCreacion = value.IdUsuario;
					}
					else
					{
						this._IdUsuarioCreacion = default(int);
					}
					this.SendPropertyChanged("TablaUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
